version: '3'
services:
  rabbitmq:
    container_name: rabbit_mq
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    build:
      context: .
      dockerfile: .docker/Dockerfile.rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

